name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Regex Search
      run: bash checkSecret.sh

    - name: Build Application
      run: npm run build

    - name: Test Application
      run: npm test

    - name: Deploy to Hosting Service
      # Add your deployment script or commands here
